### ISSUE TITLE
Null search term

### ISSUE THREAD

**Issue by cyouh95** [sien0001/codecademy-jammming#1]
In your **SearchBar** component, you have `search` set to `null` at initialization. If a user hits the "Search" button without enter a search term, then it'd be making a request to the Spotify API with `null` as the search query (ie. `https://api.spotify.com/v1/search?type=track&q=null`). 

To avoid this, in your `search()` method in **App.js**, you could first check to make sure `searchTerm` is not `null` before making a request.

https://github.com/sien0001/codecademy-jammming/blob/853715a53ac8e312f741326f697c650c35399b45/src/Components/SearchBar/SearchBar.js#L9-L11

**Comment by sien0001** [comment]
Fixed with commit 06d03fd.
