### ISSUE TITLE
Include keys in list

### ISSUE THREAD

**Issue by cyouh95** [sien0001/codecademy-jammming#2]
For generating your list of tracks, it'd be a good idea to give each item a unique **key** (ie. add `key={track.id}` to the below). This lesson explains about the importance of keys: https://www.codecademy.com/courses/react-101/lessons/react-jsx-advanced/exercises/jsx-keys?action=resume_content_item

https://github.com/sien0001/codecademy-jammming/blob/853715a53ac8e312f741326f697c650c35399b45/src/Components/TrackList/TrackList.js#L11-L17

**Comment by sien0001** [comment]
Resolved with commit 0fb8f51.
