### ISSUE TITLE
Checking for empty arrays

### ISSUE THREAD

**Issue by cyouh95** [sien0001/codecademy-jammming#3]
Alternatively, you could check for empty arrays with `!uris.length`.

https://github.com/sien0001/codecademy-jammming/blob/853715a53ac8e312f741326f697c650c35399b45/src/util/Spotify.js#L26

**Comment by sien0001** [comment]
Thanks for the pointer. I am coming from strongly typed language; this is still weird - I have to trust the runtime with "duck typing".
