### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [sien0001/codecademy-jammming#5]
(Exceeds Expectations)

Well done on this project! It looks like you have a good understanding of the overall structure of the app as well as each individual component. And great job with the requests to the Spotify API, including chaining the `.then()` methods and error handling. 

In addition, quite a unique approach you took in removing tracks added to the playlist from the search results! This does help avoid the issue with possibly adding duplicate tracks!

As a further challenge, continue to explore the Spotify API and see if you're able to add more features to this app. Happy coding!

**Comment by sien0001** [comment]
Thanks for the feedback. This was a fun project. Challenging enough, but not so obfuscated that frustration would derail from driving to completion.
